openapi: 3.0.1
info:
  title: My API
  version: 1.0.0
paths:
  /controle/{controleId}:
    get:
      summary: Handle controle with ID
      operationId: getControleById
      parameters:
        - name: controleId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:{region}:lambda:path/2015-03-31/functions/arn:aws:lambda:{region}:{account_id}:function:{lambda_function_name}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
        requestTemplates:
          application/json: |
            {
              "httpMethod": "$context.httpMethod",
              "path": "/controle-proc/$input.params('controleId')",
              "body": $input.json('$')
            }
