openapi: "3.0.0"
info:
  title: "My API"
  version: "1.0.0"
paths:
  /my-endpoint:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri: arn:aws:apigateway:region:lambda:path/2015-03-31/functions/arn:aws:lambda:region:account-id:function:MyLambdaFunction/invocations
        passthroughBehavior: WHEN_NO_TEMPLATES
        contentHandling: CONVERT_TO_TEXT
        requestTemplates:
          application/json: |
            #set($inputRoot = $input.path('$'))
            {
              "body": {
                #foreach($key in $inputRoot.keySet())
                  #set($snakeCaseKey = $util.snakeCase($key))
                  "$snakeCaseKey": "$inputRoot.get($key)"
                  #if($foreach.hasNext),#end
                #end
              }
            }
