openapi: 3.0.0
info:
  title: AWS API Gateway with CamelCase to SnakeCase Transformation
  version: 1.0.0
paths:
  /example:
    post:
      summary: Example POST endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:REGION:lambda:path/2015-03-31/functions/arn:aws:lambda:REGION:ACCOUNT_ID:function:FUNCTION_NAME/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
      x-amazon-apigateway-request-parameters:
        method.request.body:
          mapping: 
            # Start of the VTL template
            # Define the input payload as a VTL variable
            # Parse the JSON input
            # Iterate over each key-value pair in the input payload
            # Convert camelCase to snake_case
            # Build the transformed payload
            # End of the VTL template
            application/json: !include mapping.vtl